spring:
  application:
    name: ms-pedidos360-bff
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${JWT_ISSUER_URI}

server:
  port: ${SERVER_PORT:8080}

pedidos360:
  jwt:
    audience: ${JWT_AUDIENCE}
  clients:
    orders-base-url: ${ORDERS_BASE_URL:http://localhost:8081}
    catalog-base-url: ${CATALOG_BASE_URL:http://localhost:8082}
